### ISSUE TITLE
where is supStr and durationToString declaration ?

### ISSUE THREAD

**Issue by bahmany** [robicch/jQueryGantt#122]
https://github.com/robicch/jQueryGantt/blob/169b26658c238a03189c633eecc8ea120eee7dcf/ganttMaster.js#L920

**Comment by jokkopp** [comment]
jquery.min.js:2 jQuery.Deferred exception: supStr is not defined ReferenceError: supStr is not defined

**Comment by jokkopp** [comment]
i think i have the same error
i just downloaded the master project, and when i open the grantt.html file i get this error in the console

    jQuery.Deferred exception: supStr is not defined ReferenceError: supStr is not defined
      at GanttMaster.updateLinks (file:///C:/Users/youssef/Documents/Work/jQueryGantt-master/ganttMaster.js:920:83)
      at GanttMaster.loadTasks (file:///C:/Users/youssef/Documents/Work/jQueryGantt-master/ganttMaster.js:499:18)
      at GanttMaster.loadProject (file:///C:/Users/youssef/Documents/Work/jQueryGantt-master/ganttMaster.js:457:8)
      at HTMLDocument.<anonymous> (file:///C:/Users/youssef/Documents/Work/jQueryGantt-master/gantt.html:98:6)
      at j (http://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:29948)
      at k (http://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:30262) undefined r.Deferred.exceptionHook @ jquery.min.js:2

    jquery.min.js:2 Uncaught ReferenceError: supStr is not defined
       at GanttMaster.updateLinks (ganttMaster.js:920)
       at GanttMaster.loadTasks (ganttMaster.js:499)
       at GanttMaster.loadProject (ganttMaster.js:457)
       at HTMLDocument.<anonymous> (gantt.html:98)
       at j (jquery.min.js:2)
       at k (jquery.min.js:2)

**Comment by arbitora** [comment]
Having the same problem with the master.

After changing this line in ganttMaster.js (920):
`newDepsString = newDepsString + (newDepsString.length > 0 ? "," : "") + supStr+(lag==0?"":":"+durationToString(lag));`

To this fixed it for me:
`newDepsString = newDepsString + (newDepsString.length > 0 ? "," : "") + dep;`

The above line was used in an older release (see the latest commit here):
https://github.com/robicch/jQueryGantt/commit/169b26658c238a03189c633eecc8ea120eee7dcf

**Comment by robicch** [comment]
A new version of the component has been just released
